# Example Docker-Compose configuration for testing ION-DTN
# Two-node Ping: This example demonstrates a simple ping utility between ipn:10.1
#                and ipn:11.1.
# Ryan T. Moran
#
version: "3.8"
services:
  ion-node-1:
    image: local/ion-dtn:latest
    ports:
      - "1113/udp"
    environment:
      ION_CONFIG_PATH: "/usr/local/etc/ion/host10.rc"
    volumes:
      - ../../config/two-node:/usr/local/etc/ion:ro
    command:
      [
        "bpecho", "ipn:10.1", "-C"
      ]
    networks:
      - ion-net
  ion-node-2:
    image: local/ion-dtn:latest
    ports:
      - "1113/udp"
    environment:
      ION_CONFIG_PATH: "/usr/local/etc/ion/host11.rc"
    volumes:
      - ../../config/two-node:/usr/local/etc/ion:ro
    command:
      [
      "bping", "-C", "ipn:11.1", "ipn:10.1"
      ]
    networks:
      - ion-net
networks:
  ion-net:
